# Generated by Django 4.1.5 on 2023-02-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nacionalidad'),
        ),
    ]
