# Generated by Django 4.1.5 on 2023-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countries',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
