# Generated by Django 4.1.5 on 2023-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_state_countries_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
