# Generated by Django 4.1.5 on 2023-02-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('initial', models.CharField(max_length=6, unique=True, verbose_name='Lenjuage')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'db_table': 'lenguaje',
                'ordering': ['initial'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Subtitulo')),
                ('front_page', models.ImageField(blank=True, null=True, upload_to='frontpage', verbose_name='Portada')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publicher_date', models.DateField(verbose_name='Fecha de publicacion')),
                ('author', models.ManyToManyField(to='authors.author', verbose_name='Author')),
                ('gender', models.ManyToManyField(to='books.gender', verbose_name='Genero')),
                ('lenguaje', models.ManyToManyField(to='books.lenguaje', verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
    ]
