# Generated by Django 4.1.5 on 2023-02-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
                'db_table': 'gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Subtitulo')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publicher_date', models.DateField(verbose_name='Fecha de publicacion')),
                ('lenguaje', models.CharField(max_length=50, verbose_name='Lenguaje')),
                ('author', models.ManyToManyField(to='authors.author', verbose_name='Author')),
                ('gender', models.ManyToManyField(to='books.gender', verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
    ]
