# Generated by Django 4.1.5 on 2023-02-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=6, unique=True, verbose_name='Lenjuage')),
            ],
            options={
                'verbose_name': 'Lenguaje',
                'verbose_name_plural': 'Lenguajes',
                'db_table': 'lenguaje',
                'ordering': ['initial'],
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='lenguaje',
        ),
        migrations.AddField(
            model_name='book',
            name='lenguaje',
            field=models.ManyToManyField(to='books.lenguaje', verbose_name='Lenguaje'),
        ),
    ]
