# Generated by Django 4.1.5 on 2023-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_front_page_book_state_gender_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lenguaje',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
